spring:
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 480797934@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: dalbbhckattjcbee
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tRpWutP7Kdvw3ZKdRez
      secret-key: KYFqX3J2zDw8suaAIMZvxObgIVMYSA
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-chenle
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5

server:
  port: 30000
